spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/telegram_bot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:changelog/changelog-master.yaml
    parameters:
      daily_message_file_path: classpath:changelog/data/daily_message.csv
      sentence_file_path: classpath:changelog/data/sentences.csv

logging:
  config: classpath:logback.xml

meme-api:
  url: http://localhost:8443

bot:
  # username: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # token: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # winner_name: <<PROVIDE USING ENVIRONMENT VARIABLES>>

  response-chance: 0.03

schedule:
  daily-message: 0 0 12 * * *
  winner-reset: 0 0 0 * * *
  meme-post: 0 0 * * * *

