spring:
  datasource:
    url: jdbc:postgresql://localhost:6969/telegram_bot
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

bot:
  # username: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # token: <<PROVIDE USING ENVIRONMENT VARIABLES>>
  # winner_name: <<PROVIDE USING ENVIRONMENT VARIABLES>>

  sticker-set-names:
    - primates_uffchat
    - greatchurkobesfbi_by_fStikBot

  subreddit-names:
    - wordington
    - wunkus
    - clamworks
    - AROOOOOOO
    - THE_PACK
    - cursedcomments
    - holup
    - blursedimages

  random-response-chance: 0.2

download-media:
  path: /tmp/
  file-name: file

schedule:
  daily-message: 0 0 12 * * *
  winner-reset: 0 0 0 * * *
  meme-post: 0 0 * * * *

